#!/bin/bash

chown root:bind /etc/bind/*
if [ ! -d /etc/bind/zones ]
then
	mkdir /etc/bind/zones
fi
chown bind:bind -R /etc/bind/zones

mkdir -m 0775 -p /var/run/named
chown root:bind /var/run/named

echo "Starting named..."
exec /usr/sbin/named -u bind -f
